### ISSUE TITLE
[feat] add login check and responsive design

### ISSUE THREAD

**Issue by 21ow** [najitwo/10-Sprint-Taskify#21]
## 📝 Description

- 반응형 작업 추가

## ✅ To-Dos

- [ ] 반응형 디자인
- [ ] 로그인 체크 후 리다이렉트
- [x] 레이아웃 & 폴더 구조 재구성

**Comment by devmanta** [comment]
로그인 체크 후 리다이렉트 <- 요거는 어떤거 구상하고 계신지 구체적으론 모르지만
저희가 대부분 로그인 이후에 접근할 수 있는 페이지들이라서..
저도 비슷한거 middleware 적용은 해봤는데 이게 쿠키값을 가져와서 설정해줘야 잘되는것같아서
요거는 develop브랜치에 잇는 middleware 파일 한번 봐주시구 어떻게 적용하면 좋을지 고민했던 내용 같이 얘기해봐요!
